import Head from 'next/head'
import Login from "../components/Auth/Login"
import { useRouter } from 'next/router'
import { useEffect } from 'react';
import Header from '@/components/Template/Header';

export default function ProductsPage() {

  const router = useRouter();
  const query = router.query;

  useEffect(() => {
    const categories = query['categories'];
    if(typeof categories === "string"){
      console.log(categories.split(","));
    }
  }, [query])
  

  return (
    <>
      <Head>
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Header />
    </>
  )
}
