import Head from 'next/head'
import Login from "../components/Auth/Login"
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react';
import Header from '@/components/Template/Header';
import Products from '@/components/Products/Products';

type ParamsStateType = {
  categories: string,
  search: string
}

export default function ProductsPage() {

  const router = useRouter();
  const { query, isReady } = router;
  const { categories: paramCategories, search: paramSearch } = query;
  const [params, setParams] = useState<ParamsStateType | undefined>()

  useEffect(() => {
    if(!isReady) return;

    const categories = paramCategories ? paramCategories.toString() : ""
    const search = paramSearch ? paramSearch.toString() : "";
    
    setParams({categories: categories, search: search})
  }, [isReady])
  
  if(!params) return null;
  
  return (
    <>
      <Head>
      <title>Login</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head> 
      <Header />
      <Products params={params}/>
    </>
  )
}
